-- MASTER SYNC AUDIT MIGRATION
-- Generated by: DRE Audit
-- Purpose: Enforce consistent schema state, fix drift, and optimize performance.
-- Idempotent: Safe to run on existing DB.

-- 1. PROFILES: Strict Field Enforcement
alter table public.profiles 
add column if not exists company_name text,
add column if not exists tax_reference_number text,
add column if not exists registration_number text,
add column if not exists address text,
add column if not exists is_admin boolean default false,
add column if not exists tier text default 'Tier 1';

-- 2. SUBSCRIPTIONS: Explicit Definition (Fixes Hidden Table Drift)
create table if not exists public.subscriptions (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    plan_name text default 'Free', -- 'Free', 'Standard', 'Pro'
    status text default 'active', -- 'active', 'canceled', 'past_due'
    current_period_end timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique(user_id)
);

-- 3. COMPLIANCE DOCUMENTS: The New Truth
create table if not exists public.compliance_documents (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    category text not null, -- 'Tender', 'Financial', 'Legal'
    doc_type text not null, -- 'tax_clearance', 'bbbee', etc.
    title text,
    file_name text,
    file_url text, -- Storage path
    status text default 'valid', -- 'valid', 'warning', 'expired', 'missing'
    expiry_date date,
    reference_number text,
    metadata jsonb default '{}'::jsonb,
    issue_date date,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- 4. TENDERS: Status Integrity
-- We can't alter enum types easily in an idempotent way without block, so we check columns.
alter table public.tenders 
add column if not exists compliance_score int default 0,
add column if not exists has_rated boolean default false;

-- 5. PERFORMANCE: Indexing (The "Self-Healing" Performance Layer)
create index if not exists idx_compliance_docs_user on public.compliance_documents(user_id);
create index if not exists idx_compliance_docs_expiry on public.compliance_documents(expiry_date);
create index if not exists idx_tenders_status_active on public.tenders(status) where status != 'ARCHIVED';
create index if not exists idx_subscriptions_user on public.subscriptions(user_id);
create index if not exists idx_profiles_admin on public.profiles(id) where is_admin = true;

-- 6. SECURITY: RLS Enforcement
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.compliance_documents enable row level security;
alter table public.tenders enable row level security;

-- Policies (Re-apply using DO block to handle "already exists" errors gracefully-ish or just CREATE IF NOT EXISTS logic via DROP first)
-- Pro-Tip: Drop policy if exists is safe.

drop policy if exists "Users view own subscription" on public.subscriptions;
create policy "Users view own subscription" on public.subscriptions for select using (auth.uid() = user_id);

drop policy if exists "Users view own compliance docs" on public.compliance_documents;
create policy "Users view own compliance docs" on public.compliance_documents for select using (auth.uid() = user_id);

drop policy if exists "Users manage own compliance docs" on public.compliance_documents;
create policy "Users manage own compliance docs" on public.compliance_documents for all using (auth.uid() = user_id);

-- 7. CLEANUP: Orphaned Triggers from old logic
drop trigger if exists on_auth_user_created_trigger on auth.users; 
-- (Kept `on_auth_user_created` but sometimes named differently in older migrations)

-- 8. ANALYTICS PREP
-- Ensure Error Logs viewable by Admin
drop policy if exists "Admins view audit logs" on public.error_logs;
create policy "Admins view audit logs" on public.error_logs for select using (
  exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
);
