-- CLEANUP AUDIT MIGRATION
-- Generated by: DRE Audit
-- Purpose: Remove dead code, unused triggers, and deprecated logic.

-- 1. Remove Deprecated Triggers
-- The old logic used a direct DB-to-Email trigger which was flaky. Now using Edge Functions/Webhooks.
drop trigger if exists on_feedback_created on public.user_feedback;
drop trigger if exists on_error_logged on public.error_logs;

-- 2. Remove Deprecated Functions
drop function if exists public.trigger_admin_notification();

-- 3. Deprecation Warnings (Comments only for safety)
-- Table `public.company_documents` is DEPRECATED in favor of `public.compliance_documents`.
-- It is currently still read by `AdminService.getUserDetails` in the frontend.
-- ACTION REQUIRED: Update Frontend to read from `compliance_documents`, then DROP `company_documents`.

-- 4. VACUUM (Maintenance)
-- Signals to the DB to reclaim storage (Logic note: cannot run VACUUM inside strict transaction block of migration runners often, but good to document)
-- comment on table public.company_documents is 'DEPRECATED: Use compliance_documents';
