export const LEGAL_VERSION = "v1.0";

export const DISCLAIMER_TEXT = `
**Disclaimer: Decision Support Only**

This platform ("Tender Engine") provides decision-support tools, analytics, and AI-assisted drafting for informational purposes only. It is **NOT** a substitute for professional legal advice, expert consulting, or human judgment.

**By using this software, you acknowledge that:**
1.  **You are solely responsible** for the accuracy, completeness, and legality of all data submitted.
2.  **You retain full responsibility** for the final content and submission of any tender.
3.  **No Guarantees:** The platform does not guarantee compliance, tender acceptance, or successful bid outcomes.
4.  **AI Limitations:** Content generated by AI models may contain errors or hallucinations and must be rigorously reviewed by a qualified human professional.
`;

export const TERMS_OF_SERVICE_TEXT = `
**Terms of Service (v1.0)**

**1. Acceptance of Terms**
By accessing or using the Tender Readiness & Compliance Engine ("the Service"), you agree to be bound by these Terms. If you do not agree, you may not use the Service.

**2. Nature of Service**
The Service is a decision-support tool designed to assist civil construction entities in managing tender documentation. It does not automate legal compliance nor submit tenders on your behalf.

**3. User Responsibilities**
You agree that you are solely responsible for:
*   Verifying the accuracy of all insights and drafts generated by the Service.
*   Ensuring your tender submissions comply with all applicable laws and regulations (e.g., PFMA, CIDB regulations).
*   The final submission of any bid to the relevant authority.

**4. Limitation of Liability**
To the maximum extent permitted by South African law:
*   The Service is provided "AS IS" without warranties of any kind.
*   The Platform Owner shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the Service, including but not limited to lost profits, rejected tenders, or compliance penalties.
*   Our total liability is limited to the amount paid by you for the Service in the last 12 months.

**5. AI & Automated Content**
The Service utilizes Artificial Intelligence to generate text and analysis. You acknowledge that AI output is probabilistic and may be factually incorrect. All AI output serves as a draft only and requires human finalization.

**6. Jurisdiction**
These Terms are governed by the laws of the Republic of South Africa. Any disputes shall be subject to the exclusive jurisdiction of the South African courts.

**7. Amendments**
We reserve the right to modify these Terms at any time. Continued use of the Service constitutes acceptance of the modified Terms.
`;
